version: '3.8'

services:
  mongo:
    image: mongo
    container_name: my-mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend
    container_name: backend-api
    restart: always
    ports:
      - "5001:5001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/your-db-name
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    container_name: frontend-app
    restart: always
    ports:
      - "4300:80"
    depends_on:
      - backend

volumes:
  mongo-data:

